name: Snapshot Builds
on: 
  push:
    branches:
      - main

jobs:
  build-snapshot:
    strategy:
      # allow other OS snapshots to build even if one fails
      fail-fast: true
      matrix:
        os: [windows-latest, ubuntu-latest]
    defaults:
      run:
        shell: bash

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Revision Hash
        run: echo "SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      
      - name: Set Up Godot
        uses: chickensoft-games/setup-godot@v2.1.1
        with:
          version: 4.4.0
          use-dotnet: false
          include-templates: false

      - name: Create Export Template (Windows)
        if: matrix.os == 'windows-latest'
        run: scons platform=windows target=template_release optimize=size lto=full debug_symbols=no disable_3d=yes module_camera_enabled=no module_csg_enabled=no module_enet_enabled=no module_fbx_enabled=no module_gltf_enabled=no module_godot_physics_2d_enabled=no module_godot_physics_3d_enabled=no module_gridmap_enabled=no module_hdr_enabled=no module_interactive_music_enabled=no module_jolt_physics_enabled=no module_lightmapper_rd_enabled=no module_mbedtls_enabled=no module_meshoptimizer_enabled=no module_minimp3_enabled=no module_mobile_vr_enabled=no module_multiplayer_enabled=no module_navigation_enabled=no module_ogg_enabled=no module_openxr_enabled=no module_raycast_enabled=no module_theora_enabled=no module_upnp_enabled=no module_vhacd_enabled=no module_vorbis_enabled=no module_webrtc_enabled=no module_websocket_enabled=no module_webxr_enabled=no module_xatlas_unwrap_enabled=no

      - name: Compile Application (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          mkdir -p "build/windows"
          godot --headless --export-release "windows x86_64" "build/windows/vincent-windows-x86_64.exe"

      - name: Compile Application (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          mkdir -p "build/linux"
          godot --headless --export-release "linux x86_64" "build/linux/vincent-linux.x86_64"

      - name: Upload Windows Snapshot
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: SNAPSHOT-${{ env.SHA_SHORT }}-vincent-windows-x86_64
          path: build/windows/*
      
      - name: Upload Linux Snapshot
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: SNAPSHOT-${{ env.SHA_SHORT }}-vincent-linux-x86_64
          path: build/linux/*
